/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details take a look at the Writing Custom Plugins chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.6.1/userguide/custom_plugins.html
 */
version="1.0"
plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    id("com.github.jchanghong.jchtest") apply true
    `java-gradle-plugin`

    kotlin("jvm")  apply true
    `maven-publish`
    `java-library`
}
repositories {
    mavenLocal()
    maven("http://maven.aliyun.com/nexus/content/groups/public")
    jcenter()
    maven("http://af.hikvision.com.cn:80/artifactory/maven-down/")
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
}
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile::class.java).configureEach {
//        kotlinOptions.suppressWarnings=false
    kotlinOptions.jvmTarget="1.8"
//        kotlinOptions.verbose=true
//        kotlinOptions.javaParameters=true
//        kotlinOptions.useIR=true
    kotlinOptions.freeCompilerArgs = listOf("-Xjsr305=strict")
}
dependencies {

    api("cn.hutool:hutool-all:latest.release")

    api("org.jetbrains.kotlin:kotlin-gradle-plugin:latest.release")
    api("org.jetbrains.dokka:dokka-gradle-plugin:latest.release")
    api("org.jetbrains.kotlin:kotlin-allopen:latest.release")
    api("org.jetbrains.kotlin:kotlin-noarg:latest.release")
    api("org.springframework.boot:spring-boot-gradle-plugin:latest.release")
    api("io.spring.gradle:dependency-management-plugin:latest.release")
    api("name.remal:gradle-plugins:latest.release")
}

gradlePlugin {
    // Define the plugin
    val jch by plugins.creating {
        id = "com.github.jchanghong.jch"
        version="1.0"
        implementationClass = "com.github.jchanghong.JchGradlePlugin"
    }
}
