/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details take a look at the Writing Custom Plugins chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.6.1/userguide/custom_plugins.html
 */
version="2.3.3"
plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    id("com.github.jchanghong.jchtest") apply true
    `java-gradle-plugin`

    kotlin("jvm")  apply true
    `maven-publish`
    `java-library`
    id("com.gradle.plugin-publish") version "0.12.0"
}
repositories {
    mavenLocal()
    maven("http://maven.aliyun.com/nexus/content/groups/public")
    jcenter()
    maven("http://af.hikvision.com.cn:80/artifactory/maven-down/")
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
}
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile::class.java).configureEach {
//        kotlinOptions.suppressWarnings=false
    kotlinOptions.jvmTarget="1.8"
//        kotlinOptions.verbose=true
//        kotlinOptions.javaParameters=true
//        kotlinOptions.useIR=true
    kotlinOptions.freeCompilerArgs = listOf("-Xjsr305=strict")
}
dependencies {

    api("cn.hutool:hutool-all:latest.release")

    api("org.jetbrains.kotlin:kotlin-gradle-plugin:latest.release")
    api("org.jetbrains.dokka:dokka-gradle-plugin:latest.release")
    api("org.jetbrains.kotlin:kotlin-allopen:latest.release")
    api("org.jetbrains.kotlin:kotlin-noarg:latest.release")
    api("org.springframework.boot:spring-boot-gradle-plugin:latest.release")
    api("io.spring.gradle:dependency-management-plugin:latest.release")
    api("name.remal:gradle-plugins:latest.release")
}

//gradlePlugin {
//    // Define the plugin
//    val jch by plugins.creating {
//        id = "com.github.jchanghong.jch"
//        version="1.0"
//        implementationClass = "com.github.jchanghong.JchGradlePlugin"
//    }
//}
pluginBundle {
    website = "https://github.com/jchanghong/kotlin-lib"
    vcsUrl = "https://github.com/jchanghong/kotlin-lib.git"
    tags = listOf("kotlin", "test", "compatibility")
}
gradlePlugin {
    plugins {
        create("jchPlugin") {
            id = "com.github.jchanghong.jch"
//            version="1.0"
            displayName = "A plugin that helps you use kotlin "
            description = "A plugin that helps you use kotlin "
            implementationClass = "com.github.jchanghong.JchGradlePlugin"
        }
    }
}