/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package test.kotlin.app

import test.kotlin.lib.Library

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(Library().someLibraryMethod())
    println(App().greeting)
}
