/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package test.kotlin.app

import cn.hutool.core.util.RandomUtil
import com.github.jchanghong.http.OkHttps
import com.github.jchanghong.http.postJson
import test.kotlin.lib.Library

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(Library().someLibraryMethod())
    println(RandomUtil.randomString(120))
    println(App().greeting)
    val postJson = OkHttps.httpClient.postJson("http://127.0.0.1:9300/_sql?format=txt&pretty", """
        {
          "query": "SELECT * FROM test where name like 'abc%' LIMIT 5"
        }
    """.trimIndent())
    println(postJson)
}
