/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.jchanghong.test

import org.gradle.api.Plugin
import org.gradle.api.Project

internal fun log2(log: Any?, project: Project) {
    project.logger.quiet("set project【${project.name}】:${log.toString()}")
}

open class JchPluginExtension {
    /** 强制设置版本号，key是 group:name,或者group*/
    var mavenVersionMap:MutableMap<String,String>  = mutableMapOf()
    var message = "1Hello from GreetingPlugin"
}

/**
 * A simple 'hello world' plugin.
 * 一个工程一个对象实例
 */
class JchGradlePlugin : Plugin<Project> {
    lateinit var myExtension: JchPluginExtension
    override fun apply(project: Project) {
        myExtension = project.extensions.create("jch", JchPluginExtension::class.java)
        setPropertie(project)
        setRepositories(project)
        addPlugin(project)
        project.afterEvaluate { afterEvaluate(it) }
    }

    private fun afterEvaluate(project: Project) {
        log2("afterEvaluate()", project)
        configurationPlugin(project)
        setdependencies(project,myExtension)
        addMyTasks(project)
    }
}
