/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    kotlin("jvm")
    kotlin("plugin.jpa")
    kotlin("plugin.spring")
    application
    id("org.springframework.boot")
    id("io.spring.dependency-management")
}
kotlin{
    sourceSets {
        val test by getting {
            dependencies {
                implementation(kotlin("test-junit"))
            }
        }
        val main by getting {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.3.9")
            }
        }
    }
}



dependencies {
    implementation(project(":kotlin-lib"))
//        implementation("com.github.jchanghong:kotlin-lib:1.0.1")
        implementation("org.springframework.boot:spring-boot-starter-data-elasticsearch")
    implementation("org.springframework.boot:spring-boot-starter-web")
    testImplementation("org.springframework.boot:spring-boot-starter-test") {
        exclude(group = "org.junit.vintage", module = "junit-vintage-engine")
    }

}

application {
    // Define the main class for the application.
    mainClassName = "kotlin.app.AppKt"
}
