/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
//    kotlin("jvm")
//    kotlin("plugin.jpa")
//    kotlin("plugin.spring")
    application
//    id("org.springframework.boot")
//    id("io.spring.dependency-management")
    id("com.github.jchanghong.testplugin") apply true
}
//testplugin.message="jch"
kotlin{
    sourceSets {
        val test by getting {
            dependencies {
                implementation(kotlin("test-junit"))
            }
        }
        val main by getting {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.3.9")
            }
        }
    }
}



dependencies {
//        implementation("com.github.jchanghong:kotlin-lib:1.0.1")
        implementation("org.springframework.boot:spring-boot-starter-data-elasticsearch")
    implementation("org.springframework.boot:spring-boot-starter-web")
    testImplementation("org.springframework.boot:spring-boot-starter-test") {
        exclude(group = "org.junit.vintage", module = "junit-vintage-engine")
    }
    implementation(project(":kotlin-lib"))
    api("com.squareup.okhttp3:okhttp:4.9.0")
}

application {
    // Define the main class for the application.
    mainClassName = "test.kotlin.app.AppKt"
}
