
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    application
    id("com.github.jchanghong.testplugin") apply true
}
kotlin{
    sourceSets {
        val test by getting {
            dependencies {
//                implementation(kotlin("test-junit"))
            }
        }
        val main by getting {
            dependencies {
//                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.3.9")
            }
        }
    }
}



dependencies {
//        implementation("com.github.jchanghong:kotlin-lib:1.0.1")
        implementation("org.springframework.boot:spring-boot-starter-data-elasticsearch")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation(project(":kotlin-lib"))
}

application {
    // Define the main class for the application.
    mainClassName = "test.kotlin.app.AppKt"
}
