/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */
plugins {
    id("com.github.jchanghong.testplugin") apply true
    signing
    `maven-publish`
    `java-library`
}
kotlin{
    sourceSets {
        val test by getting {
            dependencies {
                implementation(kotlin("test-junit"))
            }
        }
        val main by getting {
            dependencies {
                api("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.3.9")
                api("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9")

                api("io.springfox:springfox-swagger2:2.9.2")
                api("io.springfox:springfox-swagger-ui:2.9.2")
                api("com.squareup.okhttp3:okhttp:4.9.0")
                api("com.baomidou:mybatis-plus-boot-starter:3.4.0")
                api("com.github.liaochong:myexcel:3.9.4")
                api("cn.hutool:hutool-all:5.4.1")
                api("com.oracle.ojdbc:ojdbc8")
                api("com.oracle.ojdbc:orai18n")
                api("mysql:mysql-connector-java")
                api("org.mariadb.jdbc:mariadb-java-client")
                api("org.postgresql:postgresql")
                implementation("org.springframework.boot:spring-boot-starter-data-redis")
                implementation("org.springframework.boot:spring-boot-starter-web")
                api("com.fasterxml.jackson.module:jackson-module-kotlin")
                api("com.fasterxml.jackson.module:jackson-module-parameter-names")
                api("com.fasterxml.jackson.datatype:jackson-datatype-jdk8")
                api("com.fasterxml.jackson.datatype:jackson-datatype-jsr310")
                implementation("org.springframework.kafka:spring-kafka")
            }
        }
    }
}
